name: CI-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with: 
          python-version: '3.10'
        
      - name: Poetry install
        run: |
         pip install poetry
         make install
         
      - name: Install lint and pytest
        run: poetry add --group dev flake8 pytest

      - name: Launch lint and pytest
        run: |
          make lint
          make test

      - name: Code Coverage
        uses: paambaati/codeclimate-action@v6.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make test-coverage
          debug: true